// apps/astro/src/components/home/proposals/Item.svelte
<script>
  import moment from 'moment';
  import { onMount } from 'svelte';

  export let proposal;

  const MAX_NAME_LENGTH = 100;

  onMount(() => {
      moment.updateLocale('en', {
        relativeTime: {
          future: '%s',
          past: '%s',
          s: 'a few seconds',
          ss: '%d seconds',
          m: 'a minute',
          mm: '%d minutes',
          h: 'an hour',
          hh: '%d hours',
          d: 'a day',
          dd: '%d days',
          w: 'a week',
          ww: '%d weeks',
          M: 'a month',
          MM: '%d months',
          y: 'a year',
          yy: '%d years',
        },
      });
    });

  function getTimeStatus(timeEnd) {
      if (timeEnd.getTime() > new Date().getTime()) {
        return {
          status: 'open',
          text: `open for ${moment(timeEnd).fromNow(true)}`,
        };
      } else {
        return {
          status: 'closed',
          text: `closed ${moment(timeEnd).fromNow(true)} ago`,
        };
      }
    }

    const timeStatus = getTimeStatus(new Date(proposal.timeEnd));

</script>

<li
  class="bg-white p-2 rounded-2xl break-words flex flex-row items-center gap-2 shadow-sm transition-all duration-200 hover:shadow-md"
>
  <img
    class="h-14 w-14 rounded-xl"
    src={`${proposal.daoPicture}_medium.png`}
    alt={proposal.daoName}
  />
  <p
    class="w-full text-ellipsis text-[18px] leading-[24px] font-poppins font-light"
  >
    {proposal.name.length < MAX_NAME_LENGTH
      ? proposal.name
      : `${proposal.name.slice(0, MAX_NAME_LENGTH - 3)}...`}
  </p>

  <div class="min-w-[100px] text-center">
    {#if new Date(proposal.timeEnd).getTime() > new Date().getTime()}
      <div class="text-xl text-black font-thin text-nowrap">open for</div>
      <div class="text-xl font-semibold text-black">
        {moment(proposal.timeEnd).fromNow(true)}
      </div>
    {:else}
      <div class="text-xl text-gold font-thin text-nowrap">closed</div>
      <div class="text-xl font-semibold text-gold">
        {moment(proposal.timeEnd).fromNow(true)}
        {"ago"}
      </div>
    {/if}
  </div>
</li>

// apps/web/app/components/table/item.tsx
import moment from "moment";
import Image from "next/image";
import Link from "next/link";
import { Poppins } from "next/font/google";

type ProposalProps = {
  id: string;
  name: string;
  timeEnd: Date;
  daoPicture: string | null;
  url: string;
};

const poppins = Poppins({
  weight: "300",
  subsets: ["latin"],
});

const poppinsBold = Poppins({
  weight: "600",
  subsets: ["latin"],
});

moment.updateLocale("en", {
  relativeTime: {
    future: "open for %s",
    past: "closed %s ago",
    s: "a few seconds",
    ss: "%d seconds",
    m: "a minute",
    mm: "%d minutes",
    h: "an hour",
    hh: "%d hours",
    d: "a day",
    dd: "%d days",
    w: "a week",
    ww: "%d weeks",
    M: "a month",
    MM: "%d months",
    y: "a year",
    yy: "%d years",
  },
});

const MAX_NAME_LENGTH = 100;

export const ProposalItem = ({ proposal }: { proposal: ProposalProps }) => {
  return (
    <Link
      className="flex w-full flex-row items-center gap-2 rounded-2xl bg-white p-2 shadow-sm transition-all duration-200 hover:shadow-md"
      href={proposal.url}
      target="_blank"
    >
      <Image
        className="h-[56px] w-[56px] rounded-md"
        height={56}
        width={56}
        src={`/${proposal.daoPicture}.svg`}
        alt={""}
      />

      <div
        className={`w-full text-ellipsis text-[18px] leading-[24px] ${poppins.className}`}
      >
        {proposal.name.length < MAX_NAME_LENGTH
          ? proposal.name
          : proposal.name.slice(0, MAX_NAME_LENGTH - 3) + "..."}
      </div>
      <div className="min-w-[100px] text-center">
        {proposal.timeEnd.getTime() > new Date().getTime() ? (
          <div className={`${poppins.className} text-xl text-dark`}>
            open for
          </div>
        ) : (
          <div className={`${poppins.className} text-xl text-gold`}>closed</div>
        )}

        {proposal.timeEnd.getTime() > new Date().getTime() ? (
          <div className={`${poppinsBold.className} text-xl text-dark`}>
            {moment(proposal.timeEnd).fromNow(true)}
          </div>
        ) : (
          <div className={`${poppinsBold.className} text-xl text-gold`}>
            {moment(proposal.timeEnd).fromNow(true)}
            {" ago"}
          </div>
        )}
      </div>
    </Link>
  );
};
